### ISSUE TITLE
Universal App Roadmap

### ISSUE THREAD

**Issue by mircea-dinoiu** [mircea-dinoiu/financial#21]
# Summary
- [x] Proper sorting

# Incomes
- [x] Implement incomes view

# Tables
- [x] Add context menu back 
- [x] Add infinite scrolling
- [x] Implement main screen creator for desktop
- [x] Add filtering
- [x] Fix table rows not selectable in main screen table

# Additional editors
- [x] Implement categories editor
- [x] Implement accounts editor
- [x] Implement account types

# Other
- [x] Reimplement discretness
- [x] Add tooltips for flags
- [x] Add tooltips for charged persons
